apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: spring-container
          image: dcordero7/springapp:latest
          ports:
            - containerPort: 6559  # Your application port
              # Leave protocol: TCP as default (assuming TCP)


---

apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot
  type: LoadBalancer  # Adjust if needed (e.g., NodePort)
  ports:
    - protocol: TCP
      port: 80  # External port to access the service (e.g., 80)
      targetPort: 6559  # Map to the container port
      # Optional: nodePort: 30000 (if using NodePort service type)